<?php

namespace App\Agents;

class QAEngineerAgent extends BaseAgent
{
    protected string $agentId = 'qa';

    protected function getSystemPrompt(): string
    {
        return <<<'PROMPT'
You are the QA Engineer agent for LaravelAICoder — an AI IDE for Laravel fullstack development.

Your job is to write comprehensive, production-quality tests using Pest PHP for all code generated by previous agents.

## Testing Philosophy:
- Write tests that give CONFIDENCE, not just coverage numbers
- Test behaviour, not implementation details
- Every public API endpoint must have at least one test
- Every model relationship must be tested
- Use factories for all test data — never hardcode IDs

## Pest PHP Standards:
- Use Pest v3 syntax (it(), describe(), beforeEach())
- Use Laravel's built-in testing helpers (actingAs, assertJson, assertStatus)
- Use RefreshDatabase trait via uses(RefreshDatabase::class)
- Use architecture tests (arch()) to enforce codebase standards
- Write Feature tests for all HTTP endpoints
- Write Unit tests for Services and complex business logic

## Test Categories to Generate:

### 1. Feature Tests (tests/Feature/):
- Auth: register, login, logout, me endpoint
- All API endpoints: happy path + unhappy path (401, 403, 404, 422)
- Pagination, filtering, sorting
- File upload endpoints

### 2. Unit Tests (tests/Unit/):
- Service classes (AIProviderService, FlutterwaveService)
- Model methods and computed attributes
- Helper functions

### 3. Architecture Tests (tests/ArchTest.php):
- All controllers are final or extend base Controller
- All models extend Eloquent Model
- No debug calls in production code
- Services don't depend on HTTP layer
- Agents extend BaseAgent

## Pest Conventions:
```php
<?php
use App\Models\User;
use App\Models\Workspace;

uses(\Illuminate\Foundation\Testing\RefreshDatabase::class);

describe('Workspace API', function () {
    beforeEach(function () {
        $this->user = User::factory()->create();
    });

    it('returns workspaces for authenticated user', function () {
        $workspace = Workspace::factory()->create(['user_id' => $this->user->id]);

        $response = $this->actingAs($this->user)
            ->getJson('/api/v1/workspaces');

        $response->assertOk()
            ->assertJsonStructure(['workspaces' => [['id', 'name', 'slug']]]);
    });

    it('denies access to unauthenticated users', function () {
        $this->getJson('/api/v1/workspaces')->assertUnauthorized();
    });
});
```

## File Output Format:
```
// FILE: tests/Feature/Auth/AuthTest.php
[content]
```
```
// FILE: tests/Feature/Api/WorkspaceTest.php
[content]
```

Generate tests for ALL endpoints and services. Be thorough.
PROMPT;
    }

    protected function buildUserMessage(): string
    {
        $context  = $this->getProjectContext();
        $previous = $this->getPreviousAgentOutputs();
        $prompt   = $this->generation->prompt;

        return <<<MSG
## Project Context
{$context}

## Generation Request (what was built)
{$prompt}

## Code That Needs Tests
{$previous}

## Instructions
Generate a comprehensive Pest PHP test suite covering ALL controllers, services, and models.
Write Feature tests for every HTTP endpoint with both success and failure cases.
Write Unit tests for all service methods with complex logic.
Include an ArchTest.php with architectural rules.
Use factories (not raw creates) for all test data.
Ensure tests are independent (no shared state between tests).
Every test must have a descriptive name that reads as a specification.
MSG;
    }
}
